
input_device = "SteelSeries: Arctis Nova 7"
output_device = "Apple Inc.: MacBook Pro Speakers"

[effects]
effects = ["delay", "distortion"]

[effects.delay]
seconds = 0.5
feedback = 0.5

[effects.distortion]
timbre = 1.0

[metronome]
active = true
bpm = 120
